site_name: System Test
theme:
    name: 'readthedocs'
    palette:
        primary: 'green'
        accent:  'blue'
    font: false 
repo_name: 'system-test'
repo_url: 'https://github.com/dev-tools-for-enterprise-java/system-test'
nav:
    - Home: index.md
    - Features:
        - features/README.md
    - Examples:
        - examples/README.md